version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    networks:
      - securenet
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres/securenet_ai
      - GANACHE_URL=http://ganache:8545
      - RYU_CONTROLLER_URL=http://ryu:8080
      - FLASK_APP=wsgi.py
      - FLASK_RUN_HOST=0.0.0.0
    networks:
      - securenet
    depends_on:
      - postgres
      - ganache
      - ryu

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=securenet_ai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - securenet

  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    command: --db /ganache-data -h 0.0.0.0
    volumes:
      - ganache_data:/ganache-data
    networks:
      - securenet

  ryu:
    build:
      context: ./backend
      dockerfile: Dockerfile.ryu
    ports:
      - "8080:8080"
      - "6653:6653"
    networks:
      - securenet

networks:
  securenet:
    driver: bridge

volumes:
  postgres_data:
  ganache_data:
