# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory
WORKDIR /ryu

# Install Ryu and other dependencies
RUN pip install ryu

# Copy the Ryu application
COPY ./ryu /ryu/app

# Expose the default Ryu ports
EXPOSE 6653 8080

# Start Ryu manager
CMD ["ryu-manager", "--verbose", "/ryu/app/sdn_controller.py"]
